version: '1.0'
services:
    shiny:
      build: .
      image: shiny_with_pkg:dps
      restart: always
      environment:
        - DB_HOST
        - DB_NAME
        - DB_USER
        - DB_CRED
      ports:
        - "${PORT}:3838"
      volumes:
        - ./shinyApp:/srv/shiny-server/
        - shiny-static:/usr/local/lib/R/site-library/shiny/www/shared/
volumes:
  shiny-static:

